name: test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Check out
        uses: actions/checkout@v3
      - name: Install
        run: |
          pip install .
      - name: Test
        run: |
          make test
